### ISSUE TITLE
Create & Load profile don't works

### ISSUE THREAD

**Issue by t1gu1** [GoXLR-on-Linux/goxlr-ui#3]
Hi and thx for your work! 

Create, Load and Clone profiles don't works.

I'm actually on **0.4.0** of the **goxlr-client** and on the **main branch** of the **goxlr-ui**.

When I double click on the profile, it loads nothing.
Otherwise, i don't see how to load one.

I try to create one and it did nothing.

Note that :
- My `goxlr-utility/mic-profiles` and my `goxlr-utility/profiles` was totaly empty when I try to create a new one.
- When i try to load one, I import directly my setting from windows and paste it in `goxlr-utility/mic-profiles` and my `goxlr-utility/profiles`, then I try to load it with the web UI. I saw them, but click did nothing.

P.S. Same thing for mic settings or general settings.

---

**My workaround** was simply to use goxlr-client commands.
- Load mic: `goxlr-client profiles microphone load "My mic settings file"`
- Load general settings: `goxlr-client profiles device load MySettingFile`

And then everything is showing fine in the WEB UI. 
If I try to create or clone a profile, it did'nt works more but the save seems to propose to overwrite. (I did'nt try to know if it works)

**Comment by t1gu1** [comment]
If it's a mismatch with the goxlr-client version and on the main branch, maybe creating a table to map which version works with the other could be a usefull thing.

Like: 
- goxlr-client 0.4.0 -> goxlr-ui 0.3.0
- goxlr-client 0.3.0 -> goxlr-ui 0.2.0

---

EDIT:
I just try to use the goxlr-ui and reset the branch on the 0.3.0 tag and it doesn't work more.

**Comment by FrostyCoolSlug** [comment]
Hi there, if you're running the UI via npm, you're likely hitting a cross origin request issue, you'll need to start the daemon with --http-enable-cors to permit it (it's generally just a security thing to help ensure external websites don't try to interact with the GoXLR). I'll leave the issue open until I've documented that!

In regards to the versioning, that definitely needs some work, I was hoping to find a CI solution that automates and puts everything together, but it's currently a manual process, I'll work on improving that in future (it's previously mapped directly to the daemon releases, I missed it on 0.4.0)

Thanks.

**Comment by FrostyCoolSlug** [comment]
Just to note, I've tagged 0.4.0 to correctly match the GoXLR Utility release.

**Comment by FrostyCoolSlug** [comment]
I'll close this for now, something to note reading this back..

The GoXLR Daemon already includes a 'matched' version of the webui embedded, after starting the Daemon you should be able to visit http://localhost:14564 to access it.

The main reason to check out this repo is more to perform dev work. I'll update the READMEs to clarify that point.

Thanks
