### ISSUE TITLE
Color Picker - Save Hex Value

### ISSUE THREAD

**Issue by donutcrab** [GoXLR-on-Linux/goxlr-ui#8]
Choosing a color with the picker is quite finicky and my inner monk couldn't handle a odd hex value, so I tried to enter it manually.

Problem is: On pressing enter with a custom hex value, the color doesn't change (not saved).

Before:
![image](https://user-images.githubusercontent.com/96080194/210383283-4bb93546-f304-46df-b272-89759f9fec6f.png)

After:
![image](https://user-images.githubusercontent.com/96080194/210383384-0b07cfff-e3ce-4029-9983-5a04f10c4b20.png)

**Comment by FrostyCoolSlug** [comment]
Thanks for the report, this was fixed in ed3e0299, which is due for release in 0.9.0 (hopefully this week some time!), I'll keep this issue open until it's released :)

**Comment by FrostyCoolSlug** [comment]
Flagging as fixed, this was released today with 0.9.0
