### ISSUE TITLE
Disable Lighting

### ISSUE THREAD

**Issue by donutcrab** [GoXLR-on-Linux/goxlr-ui#9]
Because you can't change the hex value to `#000000`, there is currently no way to disable lights.

The idea is to add a button to disable lighting (equivalent to `#000000`) in addition to https://github.com/GoXLR-on-Linux/goxlr-ui/issues/8

**Comment by FrostyCoolSlug** [comment]
While not being able to set the value has been fixed in 0.9.0, I'll look into adding a 'Clear' button as well (useful for users that don't know HEX!)

**Comment by FrostyCoolSlug** [comment]
I've added the clear button, it'll come with 0.9.0, looks simply like this:
![image](https://user-images.githubusercontent.com/574943/210387736-2bece1af-8b34-4863-9374-1629fbb214ff.png)
